# Monitors
# See https://wiki.hyprland.org/Configuring/Monitors/

monitor = eDP-1, 2560x1600@240, 0x0, 1
monitor = eDP-2, 2560x1600@240, 0x0, 1
#monitor = HDMI-A-1, 1920x1080@75, 2560x0, 1

# Any other monitor that gets plugged in: preferred resolution, placed automatically
monitor = , preferred, auto, 1
